theme: minima
title: Adam Levonian
author: a-location-1
description: Project Portfolio

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md

url: https://a-location-1.github.io/

minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/a-location-1/" }

